server:
  port: 5000

spring:
  application:
    name: springcloud-zipkin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    org:
      springframework:
        web: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/,http://localhost:8889/eureka/
