server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka2:8889/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: eureka1

spring:
  application:
    name: eureka-server
