server:
  port: 5002
spring:
  application:
    name: springcloud-stream
  rabbitmq:
    host: 192.168.56.105
    port: 5672
    username: guest
    password: guest
  cloud:
    function:
      definition: log;uppercase
